ansible_connection: ssh
ansible_user: rocky

ansible_ssh_private_key_file: "/var/lib/jenkins/workspace/{{ lookup('env','JOB_NAME') }}/ansible/files/deploy_key"

ansible_ssh_common_args: >
  -o IdentitiesOnly=yes
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o ControlMaster=no

