$ANSIBLE_VAULT;1.1;AES256
66633838646161393339636665636435373533616239316236623037363136346637376130623837
6634623062326332346135306130373733646134643466300a633732363030373136376265346538
65616532323539376166633330326238333163343966376564323939363539396663633663303634
6261623261616330370a643065353166373435343539373730636138396338393434346534653831
61343630313064623964313330333566613837303436613330666130613633613063
